version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/omispeech_windows"
    schedule:
      interval: "daily"