name: omispeech_linux
description: Linux implementation of the omispeech plugin
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: omispeech
    platforms:
      linux:
        pluginClass: OmispeechPlugin
        dartPluginClass: OmispeechLinux

dependencies:
  flutter:
    sdk: flutter
  omispeech_platform_interface:
    path: ../omispeech_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
