name: omispeech
description: My new Flutter package
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: omispeech_android
      ios:
        default_package: omispeech_ios
      linux:
        default_package: omispeech_linux
      macos:
        default_package: omispeech_macos
      web:
        default_package: omispeech_web
      windows:
        default_package: omispeech_windows

dependencies:
  flutter:
    sdk: flutter
  omispeech_android:
    path: ../omispeech_android
  omispeech_ios:
    path: ../omispeech_ios
  omispeech_linux:
    path: ../omispeech_linux
  omispeech_macos:
    path: ../omispeech_macos
  omispeech_platform_interface:
    path: ../omispeech_platform_interface
  omispeech_web:
    path: ../omispeech_web
  omispeech_windows:
    path: ../omispeech_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
