name: omispeech_macos
description: MacOS implementation of the omispeech plugin
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: omispeech
    platforms:
      macos:
        pluginClass: OmispeechPlugin
        dartPluginClass: OmispeechMacOS

dependencies:
  flutter:
    sdk: flutter
  omispeech_platform_interface:
    path: ../omispeech_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
