name: omispeech_windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/omispeech_windows.yaml"
      - "omispeech_windows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/omispeech_windows.yaml"
      - "omispeech_windows/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.13.2
      working_directory: omispeech_windows

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1

